services:
  - type: redis
    name: tierlist-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: web
    name: tierlist-backend
    env: node
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/main.js
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          name: tierlist-redis
          type: redis
          property: connectionString
      - key: NODE_ENV
        value: production

  - type: web
    name: tierlist-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://tierlist-backend-ptki.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
